"""initial schema

Revision ID: a5be80babd8c
Revises: 
Create Date: 2026-08-04 01:43:20.686633+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
revision: str = 'a5be80babd8c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before evidence_chunk.embedding is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('language', 'database', 'cloud', 'infra', 'ml', 'framework', 'practice', 'domain', 'soft', name='skill_category'), nullable=False),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_canonical_skill_category'), 'canonical_skill', ['category'], unique=False)
    op.create_table('evidence_chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.Column('heading', sa.String(length=512), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('evidence_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_ref', 'ordinal', name='uq_chunk_source_ordinal')
    )
    op.create_index('ix_chunk_live', 'evidence_chunk', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_chunk_text_sha256'), 'evidence_chunk', ['text_sha256'], unique=False)
    op.create_table('evidence_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('bumped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_evidence_version_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feed_sha256', sa.String(length=64), nullable=True),
    sa.Column('total_seen', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('deactivated_count', sa.Integer(), nullable=False),
    sa.Column('reactivated_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('llm_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_llm_cache_kind'), 'llm_cache', ['kind'], unique=False)
    op.create_table('posting',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('simplify_id', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_host', sa.String(length=255), nullable=True),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sponsorship', sa.String(length=128), nullable=True),
    sa.Column('role_type', sa.String(length=64), nullable=True),
    sa.Column('start_season', sa.String(length=64), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_index('ix_posting_active_feed', 'posting', ['inactive_at', 'posted_at'], unique=False)
    op.create_index('ix_posting_last_seen', 'posting', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_posting_role_type'), 'posting', ['role_type'], unique=False)
    op.create_index(op.f('ix_posting_simplify_id'), 'posting', ['simplify_id'], unique=False)
    op.create_index(op.f('ix_posting_url_host'), 'posting', ['url_host'], unique=False)
    op.create_table('run_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_metric_run_id'), 'run_metric', ['run_id'], unique=False)
    op.create_index('ix_run_metric_stage_metric', 'run_metric', ['stage', 'metric', 'recorded_at'], unique=False)
    op.create_table('evidence_skill',
    sa.Column('evidence_chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['canonical_skill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_chunk_id', 'canonical_skill_id')
    )
    op.create_table('match',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('posting_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('jd_sha256', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verdict', sa.Enum('strong', 'plausible', 'stretch', 'no', name='verdict'), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id', 'evidence_version', 'prompt_version', 'model_id', 'jd_sha256', name='uq_match_cache_key')
    )
    op.create_index('ix_match_stale', 'match', ['is_stale', 'posting_id'], unique=False)
    op.create_table('posting_jd',
    sa.Column('posting_id', sa.BigInteger(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('fetch_status', sa.Enum('pending', 'ok', 'not_found', 'rate_limited', 'transient_error', 'permanent_error', 'robots_denied', 'unsupported', name='fetch_status'), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_index(op.f('ix_posting_jd_adapter'), 'posting_jd', ['adapter'], unique=False)
    op.create_index(op.f('ix_posting_jd_fetch_status'), 'posting_jd', ['fetch_status'], unique=False)
    op.create_index(op.f('ix_posting_jd_text_sha256'), 'posting_jd', ['text_sha256'], unique=False)
    op.create_table('posting_requirement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('posting_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_skill_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('importance', sa.Enum('required', 'preferred', 'mentioned', name='importance'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['canonical_skill.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id', 'raw_text', 'prompt_version', name='uq_requirement_posting_raw_prompt')
    )
    op.create_index(op.f('ix_posting_requirement_posting_id'), 'posting_requirement', ['posting_id'], unique=False)
    op.create_index('ix_requirement_skill_importance', 'posting_requirement', ['canonical_skill_id', 'importance'], unique=False)
    op.create_table('shortlist_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('posting_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('coarse_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('evidence_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'posting_id', name='uq_shortlist_run_posting')
    )
    op.create_index(op.f('ix_shortlist_entry_run_id'), 'shortlist_entry', ['run_id'], unique=False)
    op.create_table('skill_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_skill_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('alias_norm', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['canonical_skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_norm')
    )
    op.create_index(op.f('ix_skill_alias_canonical_skill_id'), 'skill_alias', ['canonical_skill_id'], unique=False)
    op.create_table('skill_alias_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.String(length=512), nullable=False),
    sa.Column('raw_norm', sa.String(length=512), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('example_posting_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'promoted', name='candidate_status'), nullable=False),
    sa.Column('resolved_skill_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['example_posting_id'], ['posting.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_skill_id'], ['canonical_skill.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_norm')
    )
    op.create_index(op.f('ix_skill_alias_candidate_status'), 'skill_alias_candidate', ['status'], unique=False)
    op.create_table('match_citation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_skill_id', sa.Integer(), nullable=True),
    sa.Column('evidence_chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('evidenced', 'weak', 'absent', name='citation_status'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.CheckConstraint("status <> 'evidenced' OR evidence_chunk_id IS NOT NULL", name='ck_evidenced_requires_chunk'),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['canonical_skill.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunk.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_citation_canonical_skill_id'), 'match_citation', ['canonical_skill_id'], unique=False)
    op.create_index(op.f('ix_match_citation_match_id'), 'match_citation', ['match_id'], unique=False)
    # ### end Alembic commands ###

    # Approximate-nearest-neighbour index on the evidence corpus.
    #
    # hnsw over ivfflat: the corpus is small (hundreds of chunks) and is rebuilt
    # whenever evidence_version bumps. ivfflat needs representative data present at
    # build time to pick useful lists; hnsw does not, and it degrades more gracefully
    # as rows are added incrementally. vector_cosine_ops because embeddings are L2
    # normalized, so cosine is the metric the ranking code uses.
    op.execute(
        "CREATE INDEX ix_evidence_chunk_embedding_hnsw "
        "ON evidence_chunk USING hnsw (embedding vector_cosine_ops)"
    )

    # Singleton row for the corpus version counter.
    op.execute(
        "INSERT INTO evidence_version (id, version, bumped_at, reason) "
        "VALUES (1, 1, now(), 'initial') ON CONFLICT (id) DO NOTHING"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_evidence_chunk_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_citation_match_id'), table_name='match_citation')
    op.drop_index(op.f('ix_match_citation_canonical_skill_id'), table_name='match_citation')
    op.drop_table('match_citation')
    op.drop_index(op.f('ix_skill_alias_candidate_status'), table_name='skill_alias_candidate')
    op.drop_table('skill_alias_candidate')
    op.drop_index(op.f('ix_skill_alias_canonical_skill_id'), table_name='skill_alias')
    op.drop_table('skill_alias')
    op.drop_index(op.f('ix_shortlist_entry_run_id'), table_name='shortlist_entry')
    op.drop_table('shortlist_entry')
    op.drop_index('ix_requirement_skill_importance', table_name='posting_requirement')
    op.drop_index(op.f('ix_posting_requirement_posting_id'), table_name='posting_requirement')
    op.drop_table('posting_requirement')
    op.drop_index(op.f('ix_posting_jd_text_sha256'), table_name='posting_jd')
    op.drop_index(op.f('ix_posting_jd_fetch_status'), table_name='posting_jd')
    op.drop_index(op.f('ix_posting_jd_adapter'), table_name='posting_jd')
    op.drop_table('posting_jd')
    op.drop_index('ix_match_stale', table_name='match')
    op.drop_table('match')
    op.drop_table('evidence_skill')
    op.drop_index('ix_run_metric_stage_metric', table_name='run_metric')
    op.drop_index(op.f('ix_run_metric_run_id'), table_name='run_metric')
    op.drop_table('run_metric')
    op.drop_index(op.f('ix_posting_url_host'), table_name='posting')
    op.drop_index(op.f('ix_posting_simplify_id'), table_name='posting')
    op.drop_index(op.f('ix_posting_role_type'), table_name='posting')
    op.drop_index('ix_posting_last_seen', table_name='posting')
    op.drop_index('ix_posting_active_feed', table_name='posting')
    op.drop_table('posting')
    op.drop_index(op.f('ix_llm_cache_kind'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_table('ingest_run')
    op.drop_table('evidence_version')
    op.drop_index(op.f('ix_evidence_chunk_text_sha256'), table_name='evidence_chunk')
    op.drop_index('ix_chunk_live', table_name='evidence_chunk')
    op.drop_table('evidence_chunk')
    op.drop_index(op.f('ix_canonical_skill_category'), table_name='canonical_skill')
    op.drop_table('canonical_skill')
    # ### end Alembic commands ###
